---
- name: bashrc
  copy:
    src: "{{ playbook_dir }}/../dotfiles/bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    force: yes
  tags: [dotfiles]

- name: bash_functions
  copy:
    src: "{{ playbook_dir }}/../dotfiles/bash_functions"
    dest: "{{ ansible_user_dir }}/.bash_functions"
    force: yes
  tags: [dotfiles]

- name: bash_profile
  copy:
    src: "{{ playbook_dir }}/../dotfiles/bash_profile"
    dest: "{{ ansible_user_dir }}/.bash_profile"
    force: yes
  tags: [dotfiles]

- name: bash_prompt
  copy:
    src: "{{ playbook_dir }}/../dotfiles/bash_prompt"
    dest: "{{ ansible_user_dir }}/.bash_prompt"
    force: yes
  tags: [dotfiles]

- name: gitignore_global
  copy:
    src: "{{ playbook_dir }}/../dotfiles/gitignore_global"
    dest: "{{ ansible_user_dir }}/.gitignore_global"
    force: yes
  tags: [dotfiles]

- name: pryrc
  copy:
    src: "{{ playbook_dir }}/../dotfiles/pryrc"
    dest: "{{ ansible_user_dir }}/.pryrc"
    force: yes
  tags: [dotfiles]

- name: tmux.conf
  copy:
    src: "{{ playbook_dir }}/../dotfiles/tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    force: yes
  tags: [dotfiles]
