---
- name: nvim config directory
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
  tags: [neovim, dotfiles]

- name: init.vim
  copy:
    src: "{{ playbook_dir }}/../dotfiles/vimrc"
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"
    force: yes
  tags: [neovim, dotfiles]

- name: vimrc.bundles
  copy:
    src: "{{ playbook_dir }}/../dotfiles/vimrc.bundles"
    dest: "{{ ansible_user_dir }}/.config/nvim/vimrc.bundles"
    force: yes
  tags: [neovim, dotfiles]

- name: create nvim autoloads
  file:
    path: "{{ ansible_user_dir }}/.config/nvim/autoload"
    state: directory
  tags: [neovim]

- name: vim-plug (pinned version)
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/0.14.0/plug.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/autoload/plug.vim"
    checksum: sha256:20b4c895f98d13848204698068c4dd031730d4e7c9c4b630d6273b9b9afcdcdb
  tags: [neovim]

- name: install vim plugins
  command: nvim +'PlugInstall --sync' +qa
  args:
    creates: "{{ ansible_user_dir }}/.config/nvim/plugged"
  tags: [neovim]
